### ISSUE TITLE
Can't install bonzai-pomo

### ISSUE THREAD

**Issue by acagastya** [rwxrob/pomo#1]
The readme says to install pomo by running `go install github.com/rwxrob/bonzai-pomo@latest`, but that results in the following error.
```
go: github.com/rwxrob/bonzai-pomo@latest: module github.com/rwxrob/bonzai-pomo: git ls-remote -q origin in /Users/johndoe/go/pkg/mod/cache/vcs/c91abc4e242d7b05396fd57321507be373c8cd0e9703c64ef46b5ccb31c1333b: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
```

Any idea how to set it up?

**Comment by slidesecurity** [comment]
If you change the repo to how it's named now, it also breaks.
`go install github.com/rwxrob/pomo@latest`

> go: downloading github.com/rwxrob/pomo v0.0.0-20220219035717-e218e3ba3cc6
> go: github.com/rwxrob/pomo@latest: github.com/rwxrob/pomo@v0.0.0-20220219035717-e218e3ba3cc6: parsing go.mod:
> 	module declares its path as: github.com/rwxrob/bonzai-pomo
> 	        but was required as: github.com/rwxrob/pomo

**Comment by rwxrob** [comment]
Should work now that it has been fully deployed as a Bonzai tree.
