### ISSUE TITLE
timer output with 20s count down always on

### ISSUE THREAD

**Issue by NationAdel** [rwxrob/pomo#4]
Hi,

I am running on MacOS BigSur the shell is zsh 5.8 (x86_64-apple-darwin20.0) and pomo is great.
I am getting the output as 24:59(19). what ever in the parens is always counting down from 20s and resetting. I never used YAML it would help with an example config. I tried adding some configs, but it did not work. so I am guessing it should't be there.

**Comment by rwxrob** [comment]
For the time you can do `pomo var edit` and change the `interval=` to blank.
